index:
   path: /
   defaults: { _controller: 'App\Controller\TPZController::index' }

index2:
   path: /
   defaults: { _controller: 'App\Controller\TPZController::index2' }
# first, run composer req annotations
controllers:
    resource: ../src/Controller/
    type: annotation
